version: "3"
services: 
  api:
    image: node:12.18.4
    ports:
      - 3000:3000
    volumes: 
      - type: bind
        source: ./api
        target: /code
    working_dir: /code 
    command: bash -c "npm install && npm run start"
  client:
    image: node.12.18.4
    ports:
      - 8080:8080
    volumes: 
      - type: bind
        source: ./client
        target: /code
    working_dir: /code 
      depends_on:
      - db
    command: [ "http-server" ]
  db:
