version: "3"
services:
  api:
    image: node:12.18.4
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=shelterpass
      - PGDATABASE=journal
      - PGPORT=5432
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=journal
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=shelterpass
volumes:
  dbdata:
